### ISSUE TITLE
Dynamic interpolations in css functions with units stop working from 4.0.0-beta.0 and break next line

### ISSUE THREAD

**Issue by chentsulin** [callstack/linaria#1141]
## Environment

- Linaria version: 4.0.0-beta.0~4.2+
- Bundler (+ version): Next.js 13.0.2
- Node.js version: v18.12.1
- OS: macOS 12 

## Description

Using dynamic interpolations in the `rotate` function with the `deg` unit likes below:

```tsx
import { styled } from '@linaria/atomic';

const DESKTOP_IMAGE_SIZE = 200;

const ImageContainer = styled.div<{
  $rotateDeg: number;
}>`
  transform: rotate(${props => props.$rotateDeg}deg);
  width: ${DESKTOP_IMAGE_SIZE}px;
`;
```

`200;px;` in the next line is not a valid css syntax:

```css
.atm_tr_18309cv{transform:rotate(var(--y6125t));}
.atm_vy_ihe24z{width:200;px;}
```

Replacing `rotate/deg` with `calc/px` gets similar result: 

```tsx
import { styled } from '@linaria/atomic';

const DESKTOP_IMAGE_SIZE = 200;

const ImageContainer = styled.div<{
  $rotateDeg: number;
}>`
  transform: calc(${props => props.$rotateDeg}px);
  width: ${DESKTOP_IMAGE_SIZE}px;
`;
```

```css
.atm_tr_1s6q6zr{transform:calc(var(--13weht2));}
.atm_vy_ihe24z{width:200;px;}
```

This usage works with Linaria v3.0.0-beta.22 and stops working from v4.0.0-beta.0
