### ISSUE TITLE
no value no css

### ISSUE THREAD

**Issue by zomem** [callstack/linaria#1281]
```jsx
const Line = styled(div)`
  background-color: ${props => props.bgColor};
  margin-left: ${props => props.margin};
`
```

if `bgColor='#fff'` and `margin=''`，
```css
.iafj32jaf{
  background-color: #fff;
}
```
Just like this, `margin` has no value, and the generated css has no `margin-left`. How to implement it.🤔
