### ISSUE TITLE
Modifiers

### ISSUE THREAD

**Issue by ilyalesik** [callstack/linaria#355]
## Describe the feature

Describe styled component with `.withModifiers`:
```javascript
import React from "react";
import styled from "linaria";

const Button = styled.button`
    display: flex;
    height: 60px;
`.withModifiers({
    active: `
        background: red;
    `,
    disabled: `
        opacity: 0.5
    `
});
```

#### Using
Apply modifier:
```javascript
<Button modifiers="active" />
```
Apply multiple modifiers:
```javascript
<Button modifiers={["active", "disabled"]} />
```
Referring (if it possible):

```javascript
const OtherComponent = styled.div`
    ${Button.active}:hover & {
        color: white;
    }
`; 
```
#### Output code
```css
.Button-df5234f {
    display: flex;
    height: 60px;
}
.Button--active-45df53 {
    background: red;
}
.Button--disabled-j84jje {
    opacity: 0.5;
}
```

## Motivation
Good type inference at static type checkers (TS, Flow). Non declared specifier will throw typing error:
```javascript
// TypeError: field 'foo' is not declared
<StyledComponent modifiers="foo" />
```
