### ISSUE TITLE
url() processing on Windows not working

### ISSUE THREAD

**Issue by lithiumfallen** [callstack/linaria#391]
## Environment

`Windows 10`
`linaria@1.3.1`
`webpack@4.26.0`

## Description

If I use `url()` like that `background: url(./image/logo.svg)` after compile in `.linaria-cache` I have something like that `.\..\..\..\..\..\src\search\card\image\logo.svg`. And the next step build will be broken. I found that `https://github.com/callstack/linaria/blob/master/src/transform.js#L113` operate `url()`. Maybe on this step should replace backslashes or use specific methods for os? On linux base and macos works well.

**Comment by ivancuric** [comment]
Perhaps the same error as https://github.com/callstack/linaria/issues/368?

**Comment by pbitkowski** [comment]
Thanks for submission @lithiumfallen. It looks like @ivancuric is right. I will close this issue for now and please check #368 for updates.

**Comment by lithiumfallen** [comment]
Hi all, sorry for lateness. I think it's different issues and relation with processing paths for different os. For example I have svg logo `logo.svg` and i wanna process. As want to process in background. 
```jsx
const Component = styled.div`
    background: url(./logo.svg);
`
``` 
Before linaria/loader processing I have css style
```css
.className {
     background: url(.\..\..\..\..\..\src\search\card\image\logo.svg);
}
```
When I try build this css file will be process loaders from webpack. And this path will be parce with  escaping like this
```css
...........srcsearchcardimagelogo.svg
```
the problem is for windows should add escaping and path after linaria/loader compile should be like this
```
url(.\\..\\..\\..\\..\\..\\src\\search\\card\\image\\logo.svg);
or
url(./../../../../../src/search/card/image/logo.svg);
```
And result css in my case should be 
```css
.className {
     background: url(base64-image-inline-if-logo-less-then-size-in-config);
}
```
On POSIX OS all is okay.
