### ISSUE TITLE
Unexpected result using `:is() &`

### ISSUE THREAD

**Issue by nstepien** [callstack/linaria#782]
## Environment

- Linaria version: 3.0.0-beta.6
- Bundler (+ version): rollup@^2.51.2
- Node.js version: v16.3.0
- OS: win10

## Description

`:is(...) &` incorrectly adds the generated class before `:is()`.
I don't know if this is an issue with Linaria or a sub-dependency.

## Reproducible Demo

```js
css`
  :is(div, span) & {
    color: red;
  }
`;
```

This becomes
```css
.s1waqsbb:is(div,span) .s1waqsbb{color:red}
```
Instead I expect the following
```css
:is(div,span) .s1waqsbb{color:red}
```

**Comment by Anber** [comment]
Hi @nstepien 

It happens because styles are isolated in the current scope by default. If you want to define a selector outside a scope, you can use `:global` operator:
```
css`
  :global(:is(div, span) &) {
    color: red;
  }
`;
```

**Comment by nstepien** [comment]
I see, thanks. I guess it happens with all selectors starting with `:`? I thought `&` would always override the default behavior/scoping.

input:
```js
css`
  .a {
    .b & {
      color: blue;
    }
  }
`;

css`
  .c {
    :hover & {
      color: red;
    }
  }
`;
```

output:
```css
.b .s1waqsbb .a {
  color: #00f;
}

.syp60te .c:hover .syp60te .c {
  color: red;
}
```

**Comment by nstepien** [comment]
@Anber Actually it doesn't work for my case:

input:
```js
const parentA = css``;
const parentB = css``;
const parentC = css``;
const activeLink = css``;

const link = css`
  all: unset;

  :is(:hover, :focus, .${activeLink}) {
    color: red;

    :global(:is(.${parentA}, .${parentB}) &) {
      content: '';
    }

    .${parentC} & {
      color: blue;
    }
  }
`;
```
output:
```css
.lc7u01 {
  all: unset;
}

.lc7u01:is(:hover, :focus, .a1lslk66) {
  color: red;
}

:is(.p1waqsbb, .pyp60te) .lc7u01 {
  content: "";
}

.p4g1w4s .lc7u01:is(:hover, :focus, .a1lslk66) {
  color: #00f;
}
```

I would have expected this instead
```diff
-:is(.p1waqsbb, .pyp60te) .lc7u01 {
+:is(.p1waqsbb, .pyp60te) .lc7u01:is(:hover, :focus, .a1lslk66) {
```
I know I can do `.${parentA} &,, .${parentB} & {}`, but that defeats the optimizations `:is()` offers.

Can we reopen this issue?
