### ISSUE TITLE
Rollup & PostCSS generates wrong style files with esm output + preserveModules

### ISSUE THREAD

**Issue by FancyVase** [callstack/linaria#818]
## Environment
- linaria: `^3.0.0-beta.4`
- rollup: `^2.5.6`
- node: `13.8.0`
- OS: `macOS Mojave 10.14.6`

## Description

I'm using Rollup with `@linaria/rollup` + `rollup-plugin-postcss` to bundle React components that inject their styles on hydration.

I also have an output format of `esm` w/ `preserveModules: true` in order to support tree-shaking.

With this configuration, style files get generated incorrectly. Specifically, the built component JS file looks like this:

```js
import React from 'react';
import { styled } from '@linaria/react';
import '../_virtual/LinariaComponent.jsx_52jihk.css';

var Wrapper = /*#__PURE__*/styled("div")({
  name: "Wrapper",
  "class": "w195sr2l"
});
var LinariaComponent = function LinariaComponent() {
  return /*#__PURE__*/React.createElement(Wrapper, null);
};

export { LinariaComponent };
//# sourceMappingURL=LinariaComponent.js.map
```

I would expect a `.js` import on the third line instead of `import '../_virtual/LinariaComponent.jsx_52jihk.css';`

Opening that file gives me:

```css
import styleInject from '../node_modules/style-inject/dist/style-inject.es.js';

var css_248z = ".w195sr2l{background-color:pink;}";
styleInject(css_248z);

export { css_248z as default };
//# sourceMappingURL=LinariaComponent.jsx_52jihk.css.map
```

Which is valid JS, but not valid CSS, and so attempting to use this component errors out.

This issue only appears when I set the Rollup `output.format` to `'esm'` and set `preserveModules: true`, which I have to support tree-shaking.

-------

## Reproducible Demo

Repo: https://github.com/FancyVase/test-linaria-rollup-postcss

I have a second `PostcssComponent.jsx` file that gets bundled as expected when importing a `.pcss` file.

I also included an `esm` output without `preserveModules` as well as a `cjs` output, both of which work as expected.
